services:
  php:
    build:
      context: .
      args:
        USER_ID: 1000  # ваш UID на хосте
        GROUP_ID: 1000 # ваш GID на хосте
    volumes:
      - .:/app
      - ../core:/app/vendor/rift/core
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /app
    environment:
      APP_ROOT: /app # явно указываем корень проекта
      COMPOSER_MEMORY_LIMIT: -1
    command: bash -c "composer install && php-fpm"

  nginx:
    image: nginx:alpine
    ports:
      - "84:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  composer:
      image: composer:2
      user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
      volumes:
        - .:/app
        - ./../core:/app/../core  # Монтируем core
      working_dir: /app
      environment:
        COMPOSER_HOME: /tmp/composer

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-rift}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8086:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD:-admin}
    depends_on:
      - postgres
    
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP порт для отправки писем
      - "8025:8025" # Web UI
  
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mysql_data:
  redis_data:
  postgres_data: