<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Rift\\Contracts\\Http\\ResponseEmitter\\EmitterInterface' => 'get1',
  'Rift\\Contracts\\Http\\Router\\RouterInterface' => 'get2',
  'Rift\\Core\\Http\\ResponseEmitters\\CompositeEmitter' => 'get3',
  'subEntry1' => 'get4',
  'subEntry2' => 'get5',
  'subEntry3' => 'get6',
  'subEntry4' => 'get7',
  'Rift\\Core\\Http\\ResponseEmitters\\JsonEmitter' => 'get8',
  'Rift\\Core\\Http\\ResponseEmitters\\XmlEmitter' => 'get9',
  'Rift\\Core\\Http\\ResponseEmitters\\TextEmitter' => 'get10',
  'Rift\\Core\\Http\\Router\\Router' => 'get11',
  'subEntry5' => 'get12',
  'subEntry6' => 'get13',
  'Psr\\Container\\ContainerInterface' => 'get14',
);

    protected function get1()
    {
        return $this->delegateContainer->get('Rift\\Core\\Http\\ResponseEmitters\\CompositeEmitter');
    }

    protected function get2()
    {
        return $this->delegateContainer->get('Rift\\Core\\Http\\Router\\Router');
    }

    protected function get5()
    {
        return $this->delegateContainer->get('Rift\\Core\\Http\\ResponseEmitters\\JsonEmitter');
    }

    protected function get6()
    {
        return $this->delegateContainer->get('Rift\\Core\\Http\\ResponseEmitters\\XmlEmitter');
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Rift\\Core\\Http\\ResponseEmitters\\TextEmitter');
    }

    protected function get4()
    {
        return [
            0 => $this->get5(),
            1 => $this->get6(),
            2 => $this->get7(),
        ];
    }

    protected function get3()
    {
        $object = new Rift\Core\Http\ResponseEmitters\CompositeEmitter($this->get4());
        return $object;
    }

    protected function get8()
    {
        $object = new Rift\Core\Http\ResponseEmitters\JsonEmitter();
        return $object;
    }

    protected function get9()
    {
        $object = new Rift\Core\Http\ResponseEmitters\XmlEmitter();
        return $object;
    }

    protected function get10()
    {
        $object = new Rift\Core\Http\ResponseEmitters\TextEmitter();
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('Rift\\Contracts\\Http\\RoutesBox\\RoutesBoxInterface');
    }

    protected function get13()
    {
        return $this->delegateContainer->get('Psr\\Container\\ContainerInterface');
    }

    protected function get11()
    {
        $object = new Rift\Core\Http\Router\Router($this->get12(), $this->get13());
        return $object;
    }

    protected function get14()
    {
        return $this->resolveFactory(static function (\DI\Container $container) {
        return $container;
    }, 'Psr\\Container\\ContainerInterface');
    }

}
